### PR TITLE
remove unused command change string 

### PR DESCRIPTION
**Pull request by dydrmr5**
remove unused command on telebot_data.py and change string format from f string to % string

### CODE REVIEW

**Comment by slowy07** [comment]
conflict joe,coba benerin,gass joe @dydrmr5

**Comment by slowy07** [comment]
overall,banyak yng harus diubah lgi joe,gasskan joe

**Comment by dydrmr5** [comment]
oke fy okee

**Comment by dydrmr5** [comment]
> overall,banyak yng harus diubah lgi joe,gasskan joe

siap fy sensei

**Pull request closed without merging**
